### PR TITLE
Added MyListIterator and filled out its methods

### PR DESCRIPTION
**Pull request by cs15lsp22ahg**

### CODE REVIEW

**Comment by hqy2000** [comment]
This is a serious academic integrity violation and I would recommend you to delete your repo from GitHub asap

**Comment by cs15lsp22ahg** [comment]
Sorry, I am very confused, are we not supposed to fork the existing
directory and edit it? If not, I will remove the repo (and hope it does not
delete what I’ve done).

**Comment by hqy2000** [comment]
Your repo is public, which means everyone is able to see your code. You should make a **private** repo instead.

**Comment by cs15lsp22ahg** [comment]
Oh, oops, sorry, I’ll fix that now!

**Comment by cs15lsp22ahg** [comment]
Wait, it says I can’t change the visibility of a fork.

**Comment by cs15lsp22ahg** [comment]
I deleted it. I won’t get marked off for this, right? I did that on
accident trying to implement what cse 15l taught us to do.

**Comment by hqy2000** [comment]
As long as no one copied your work, you should be fine.

**Comment by cs15lsp22ahg** [comment]
If someone did manage to what do I do? It was an honest mistake and I don’t
want to lose points because I was trying to implement cse15l techniques.

**Comment by cs15lsp22ahg** [comment]
Are you still there? You can't see it anymore, right?

**Comment by cs15lsp22ahg** [comment]
Please answer, this is really scaring me, I really don't want to have an
academic integrity violation on my record.

**Comment by cs15lsp22ahg** [comment]
Sorry, how do I delete a repo?

**Comment by hqy2000** [comment]
https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository

**Pull request closed without merging**
